export const colors = {
  background: '#fefbff',
  surface: '#fefbff',
  surfaceVariant: '#e2e1ec',
  primary: '#4658a9',
  onPrimary: '#ffffff',
  primaryContainer: '#dce1ff',
  onPrimaryContainer: '#00115a',
  secondary: '#5a5d71',
  onSecondary: '#ffffff',
  secondaryContainer: '#dfe1f9',
  onSecondaryContainer: '#171b2c',
  tertiary: '#76536e',
  onTertiary: '#ffffff',
  tertiaryContainer: '#ffd6f5',
  onTertiaryContainer: '#2d1229',
  error: '#ba1b1b',
  onError: '#ffffff',
  errorContainer: '#ffdad4',
  onErrorContainer: '#410001',
  outline: '#76767f',
  text: '#1b1b1f',
  textMuted: '#45464f',
  inversePrimary: '#b8c4ff',
  shadow: '#000000',
};